# Generated by Django 5.2.8 on 2025-11-19 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('item', models.AutoField(primary_key=True, serialize=False, verbose_name='ITEM')),
                ('documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='DOCUMENTO')),
                ('nombres_apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='NOMBRES Y APELLIDOS')),
                ('imei1', models.CharField(blank=True, max_length=100, null=True, verbose_name='IMEI 1')),
                ('imei2', models.CharField(blank=True, max_length=100, null=True, verbose_name='IMEI 2')),
                ('sn', models.CharField(blank=True, max_length=100, null=True, verbose_name='S/N')),
                ('mac_superflex', models.CharField(blank=True, max_length=100, null=True, verbose_name='MAC SUPERFLEX')),
                ('articulo', models.CharField(default='MAQUINA', max_length=100, verbose_name='ARTÍCULO')),
                ('marca', models.CharField(blank=True, choices=[('SUNMI V1', 'SUNMI V1'), ('SUNMI V2', 'SUNMI V2'), ('SUNMI V2 PRO', 'SUNMI V2 PRO'), ('N910', 'N910'), ('NEWLAND GRIS', 'NEWLAND GRIS')], max_length=20, null=True, verbose_name='MARCA')),
                ('activo', models.CharField(blank=True, max_length=100, null=True, verbose_name='ACTIVO')),
                ('cargo', models.CharField(default='vendedor ambulante', max_length=100, verbose_name='CARGO')),
                ('estado', models.CharField(default='activo confirmado', max_length=100, verbose_name='ESTADO')),
                ('fecha_confirmacion', models.DateField(auto_now_add=True, verbose_name='FECHA DE CONFIRMACIÓN')),
                ('responsable', models.CharField(blank=True, max_length=100, null=True, verbose_name='RESPONSABLE')),
                ('identificacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='IDENTIFICACIÓN')),
                ('zona', models.CharField(default='Valledupar', max_length=100, verbose_name='ZONA')),
                ('observacion', models.TextField(default='VERIFICADO', verbose_name='OBSERVACIÓN')),
                ('punto_venta', models.CharField(blank=True, max_length=100, null=True, verbose_name='PUNTO DE VENTA')),
                ('codigo_centro_costo', models.CharField(blank=True, max_length=100, null=True, verbose_name='CÓDIGO CENTRO DE COSTO')),
                ('centro_costo_punto', models.CharField(blank=True, max_length=100, null=True, verbose_name='CENTRO DE COSTO PUNTO')),
                ('fecha_salida_bodega', models.DateField(blank=True, null=True, verbose_name='FECHA DE SALIDA DE BODEGA')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_cambiado', models.CharField(max_length=100, verbose_name='Campo Cambiado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor Nuevo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.activo', verbose_name='Activo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
            },
        ),
    ]
