# Generated by Django 5.2.8 on 2025-12-01 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0007_categoria_zona'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='articulo_fk',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='activo',
            name='articulo',
        ),
        migrations.AddField(
            model_name='activo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activos.categoria', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida'), ('transferencia', 'Transferencia'), ('cambio_estado', 'Cambio de Estado')], max_length=20, verbose_name='Tipo de Trazabilidad')),
                ('zona_origen', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona Origen')),
                ('zona_destino', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zona Destino')),
                ('estado_anterior', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado Nuevo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.activo', verbose_name='Activo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Trazabilidad',
                'verbose_name_plural': 'Trazabilidad',
                'db_table': 'activos_trazabilidad',
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='Articulo',
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
    ]
