# Generated by Django 5.2.8 on 2025-12-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0011_migrate_marcas_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='iccid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ICCID'),
        ),
        migrations.AddField(
            model_name='activo',
            name='operador',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='OPERADOR'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='marca_old',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MARCA OLD'),
        ),
    ]
