# Generated by Django 5.2.8 on 2025-12-05 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0013_tranzabilidad_delete_trazabilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tranzabilidad',
            name='activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activos.activo', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tranzabilidad',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('salida', 'Salida'), ('transferencia', 'Transferencia'), ('cambio_estado', 'Cambio de Estado'), ('asignacion', 'Asignación'), ('actualizacion', 'Actualización'), ('eliminacion', 'Eliminación')], max_length=20, verbose_name='Tipo de Tranzabilidad'),
        ),
    ]
